# Unbind the old PREFIX C-b.

unbind-key C-b

# Create the focus variable.

set-option -g @focus 0

# Key bindings.

source-file ~/.tmux.bind

# Start windows and panes at 1.

set-option -g base-index 1
set-option -g -w pane-base-index 1

# Set the default shell to zsh.

set-option -g default-shell /bin/zsh

# Lord the nord theme.

run-shell "~/.tmux/themes/nord-tmux/nord.tmux"

# Convert completion BEL notifications into visual tmux window alerts.

set-window-option -g monitor-bell on
set-option -g bell-action none
set-option -g visual-bell off
set-option -g window-status-bell-style 'fg=#2e3440,bg=#ebcb8b,bold'

# Display the focus status. -a append to existing value.

set-option -ga status-right "#{?@focus,,UNFOCUS}"
